- name: Replace secrets in config yml file
  hosts: localhost
  vars_files:
    - "./automation/support/secrets.yml"  # Path to yml file containing replacement values

  tasks:
    - name: Render config with secrets
      template:
        src: "./automation/support/config.yml"  # Path to template yml file with placeholders
        dest: "./automation/support/config.yml"  # Path to the rendered yml file