name: QA Automation Framework Docker Image CI for GHCR

on:
  workflow_dispatch: # push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username JoavFernandes --password ${{ secrets.JF_GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/deus-ai/qa-automation-framework_amd64:latest
          docker push ghcr.io/deus-ai/qa-automation-framework_amd64:latest
